### ISSUE TITLE
Can't install plugin for 6.6.1 on mac

### ISSUE THREAD

**Issue by robbig2871** [codelibs/elasticsearch-dataformat#53]
latest ES version for mac is 6.6.1. 

```elasticsearch-plugin install org.codelibs:elasticsearch-dataformat:6.6.1```

returns:
```
 -> Downloading org.codelibs:elasticsearch-dataformat:6.6.1 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/codelibs/elasticsearch-dataformat/6.6.1/elasticsearch-dataformat-6.6.1.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:380)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:454)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:264)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:229)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```
Can you help?

**Comment by marevol** [comment]
Version 6.6.x of this plugin works on Elasticserach 6.6.x.
So, you can use 6.6.0.
For available plugins, see [Maven repository](http://central.maven.org/maven2/org/codelibs/elasticsearch-dataformat/).

**Comment by robbig2871** [comment]
ver 6.6.0 is ok, thx
